server:
  port: 8761
spring:
  application:
    name: eureka-server

eureka:
  client:
      register-with-eureka: false
      fetch-registry: false

  service-url:
    default-zone: http://localhost:8761/eureka

  config:
    import: optional:configserver:http://localhost:8888

    instance:
      prefer-ip-address: true







