server:
  port: 8002
  servlet:
    context-path: /catalog/

spring:
  application:
    name: catalog-service

     zipkin:
    base-url: http://localhost:9411/
    enabled: true

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3370/movie-dev
    username: usr-movie
    password: pwd-movie

  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27017

    rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
queue:
  serie:
    name: SerieQueue
  movie:
    name: MovieQueue

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

  management:
  endpoints:
    web:
      exposure:
        include: '*'
     health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      movies:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false
        automaticTransitionFromOpenToHalfOpenEnabled: true
retry:
  instances:
    catalog:
    waitDuration: 1000
    maxAttempts : 3
    retryExceptions:
      - feign.FeignException$InternalServerError
