server:
  port: 8080
  
spring:
  application:
    name: gateway
   cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: movielistRoute
          uri: lb://catalog-service/
          predicates:
            - Path=/movielist/**
    
eureka:
  client:
      register-with-eureka: true
      fetch-registry: true
      registry-fetch-interval-seconds: 5
      healthcheck:
        enabled: true
      service-url:
        default-zone: http://localhost:8761/eureka
  instance:
      prefer-ip-address: true